adminpass: "hogehuga"
rootURL: "https://"
logLevel: "debug"
#("debug", "info", "warn", "error", "dpanic", "panic", and "fatal")

worker:
  maxThread: 3

terraform:
  options:
    path: "/usr/bin/terraform"
    workingDirectory: "/deploy"
    parallelism: 4
  secrets:
    sakuraCloudAccessToken: ""
    sakuraCloudAccessTokenSecret: ""
    awsAccessKeyId: ""
    awsSecretAccessKey: ""
    cloudflareApiToken: ""
