version: "3"
services:
  terraform_agent:
    environment:
      SLACK_WEBHOOK_URL:
      DISCORD_WEBHOOK_team100:
    build: .
    network_mode: "host"
    tty: true
    #    ports:
    #      - "8089:8089"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
# tfファイルのディレクトリをマウント
#      - ../tf-dir:/deploy