// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// Defines values for RedeployStatusStatus.
const (
	RedeployStatusStatusCreating RedeployStatusStatus = "Creating"
	RedeployStatusStatusError    RedeployStatusStatus = "Error"
	RedeployStatusStatusQueuing  RedeployStatusStatus = "Queuing"
	RedeployStatusStatusRunning  RedeployStatusStatus = "Running"
)

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// QueueStatus defines model for QueueStatus.
type QueueStatus struct {
	// InQueue キューに入っているチームID_問題IDのリスト
	InQueue *[]string `json:"in_queue,omitempty"`
}

// RedeployRequest defines model for RedeployRequest.
type RedeployRequest struct {
	// ProblemId 問題ID（アルファベット形式、problem_mapping.jsonで定義）
	ProblemId string `json:"problem_id"`

	// TeamId チームID（2〜3桁の数字）
	TeamId string `json:"team_id"`
}

// RedeployStatus defines model for RedeployStatus.
type RedeployStatus struct {
	// Message 状態に関するメッセージ
	Message *string `json:"message,omitempty"`

	// Status 再展開の状態
	Status *RedeployStatusStatus `json:"status,omitempty"`

	// UpdatedAt 最終更新日時
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// RedeployStatusStatus 再展開の状態
type RedeployStatusStatus string

// PostRedeployJSONRequestBody defines body for PostRedeploy for application/json ContentType.
type PostRedeployJSONRequestBody = RedeployRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// キューの状態取得（未使用）
	// (GET /monitor)
	GetQueueStatus(c *gin.Context)
	// 再展開リクエストの送信
	// (POST /redeploy)
	PostRedeploy(c *gin.Context)
	// チーム全体のステータス取得
	// (GET /status/{teamID})
	GetTeamStatus(c *gin.Context, teamID string)
	// 特定の問題のステータス取得
	// (GET /status/{teamID}/{problemID})
	GetProblemStatus(c *gin.Context, teamID string, problemID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetQueueStatus operation middleware
func (siw *ServerInterfaceWrapper) GetQueueStatus(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetQueueStatus(c)
}

// PostRedeploy operation middleware
func (siw *ServerInterfaceWrapper) PostRedeploy(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRedeploy(c)
}

// GetTeamStatus operation middleware
func (siw *ServerInterfaceWrapper) GetTeamStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamID" -------------
	var teamID string

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamStatus(c, teamID)
}

// GetProblemStatus operation middleware
func (siw *ServerInterfaceWrapper) GetProblemStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamID" -------------
	var teamID string

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "problemID" -------------
	var problemID string

	err = runtime.BindStyledParameterWithOptions("simple", "problemID", c.Param("problemID"), &problemID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter problemID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProblemStatus(c, teamID, problemID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/monitor", wrapper.GetQueueStatus)
	router.POST(options.BaseURL+"/redeploy", wrapper.PostRedeploy)
	router.GET(options.BaseURL+"/status/:teamID", wrapper.GetTeamStatus)
	router.GET(options.BaseURL+"/status/:teamID/:problemID", wrapper.GetProblemStatus)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZW1MbRxb+K1Rv3lZGEnYeVm++btjaCzE8baylxlIbJiXNjGdazlKUquiRcQQoBbYD",
	"GBuvjR1jxRTCW7mU2Qj4Mc2MxBN/Yet0z31Gsmw2VZsnD5rpPrfvfOfr9iwqqGVNVbBCDJSbRUZhGpcl",
	"/nhV11UdHjRd1bBOZMx/LmPDkKYwPOJ/SmWthFEOMbPJat+zWpvVtlitxsxf4Nl8h1KIzGjwhUF0WZlC",
	"1RQyiEQqRng95rZiH1e9X9SbX+ICgeWfV3AFj3t7hJ2Tlcnb8B6ei9go6LJGZFXhHu6y2ivwiu5Y868Y",
	"fcnoNqN3mbnEapR7/nz0yqS1unyy1Ri9wmiL1d4wc5/V6ijle/oFymQnM1mUQpmRycx5lE8hmeCycEUi",
	"BOtg7B83bhRnR6qT4p9PkrLg/CDpujSTHOh1XMRaSZ25jm9XsEHiwWq6erOEy5NyMR6uG8dpu87MF6y2",
	"w2qrzNxitQ0oT61uHbyw2stsjrqblCVNk5Wp4S8NVWH0tdV63Dn8/rS9EAweXbx0OTEWLCV7Ecjsabs+",
	"wuY2z9tblNGWvfrW2l2Pbs/zGs1i6nxSAqsppOPbFVnHRSiK60EqmJR8n6T2AlAA3eFQOos/2/NLjO6c",
	"rL1gdIPDJgr1QD+4gQ9lskOMtkQ5nD84sA74qn1GG/buS+vdO4DlvW+sf6+erC0xusrMBqOHjK4z+qx/",
	"E0Xq7u/REi6DX0qlDFmC1oH1KXRZxxIRj9criiKeRMPng3H4L2MeVLSiRHBxUiJxL+zNuc5Ppv3kR3vt",
	"rb3+yt4wQ9kZyYxcOJfJnst+OpHN5M5ncpnM31EK3VL1MuyGYONzRC7jQRgBkoELFV0mM+NAXqKONyVD",
	"LlyskOm4c59NTIwNXYL33TffdJvt03Z9eJpokmF8VWT0dae11Vm5J6DJ2RCM8e18b6YJ0VAVTMvKLRVM",
	"FFSFSAWeCkXiS0YvT4xDt1T0krPCyKXTUzKZrtwcLqjltFwgRiFtQCUxJLRXIQEte0CwnIyY+UB4CNiY",
	"o4w+BUTBq3scUUfwbD7oPHnZ3V5zgEqfMRO67uLYKDN/4sBcYbU2xCMTXhHhxdDFsdGhcazfwcDFd7Bu",
	"CF+yw5nhDLioaliRNBnl0Pnh7HBGdOs0T3i6rCoyEQNjCjuY0HRcAJCgHNErONWbklud5UNrs+mBlpkP",
	"rOU163Cdd8AhxDFnet9b9+YZ3WHUZOaSNd/kRN7yWo7Rpmg3/uNjoD/asFZ2YB+nq2C3G4r9Q9O+u5wb",
	"YvQhz2GT1X5gtQVWe8rM7/hzndE9e/PN8cFR59smo0146zix5X6w020+6rYX3J7lM8W3gXjSdAlCHi2i",
	"HPojJsEJBjRmaKpiCNiOZDIumrDCkyhpWkku8PVp4ObQ3AwOvOhkSqHMp/B3vurgWILvP9HxLZRDv0v7",
	"Yz/tzPx00C8O7l7lcjJVB2jS1p/G//ZXf1byfqyUy5I+Ey0xr6wo62m77uVVtBqRpgwI4i8OjPKwUVp3",
	"6JoTtWqQfoQX6xPr622nT9x6uLh4w+h9Xq238VVBodA9OrAWnwd3uKFYKw1GHwUm2++jmiGwHW3Y6y8A",
	"qyHoHkJH0j3h3/G7XRgQz3+0VgBuvpIyH3SPvg3bjqFpTDWIO9KQGInYIJfU4szgMApKsSzXgF75eiaX",
	"to4PYbLckUpCbAW1iCsTXFUAc53jaTAYRnVPNTzsgUmqsbbJDhCvb34ARdsPV8vrjN4//uURoGiwIe3v",
	"KxUKWANKHGS0xXsw7EzQE7u+Yi0+A7MXPoREHNl8RyrJxWvOAA5CoHN3y1rch5aJ5AH0pFD8/xKSMggH",
	"L6UfsJ7R14xuID9tzqlAjFnu4JhA2eiVsI8++BhtCIPvcSa44r1WJ7AUM+mAGzpXKGm3bZMNe5/vjQQF",
	"MDfOp9jRfHebMtrgfy6Klk9yauAuuuov6AuhhDp4oQCWRv7wgViSSjqWijOjyufuQczPWoQMQfPuPrI2",
	"m8lJizCtJ6OTeHav19YegSaXmA/Pa5VSKexoYJ+G/Z85++lesosxcogu6w2vs1fSWmnYG2aUEuo/n2ys",
	"eDMmIZDwhO5D8Sdz9PhoKzCbvUkjhrMIKT1LeH9UQ8ovdHRa2Ldaj8MSbYfRRT6EfQHnFzemZiNaMElU",
	"QZN6mkqTdKmMCdbB7Y86lMrwJYhblHIFvQgTRWdRsIwfd5TNn1UEwryNwPJ/e/z0wOufB4PHv+QDXTWF",
	"rly9Fmnp901Va3nN5b+obf/02s/2iLAd6i6pWJQhd1JpLDT4B1Ehrh4eZDhHcBuTxoOO5jPyQmDk3mfm",
	"flSSu9iw5pvHBw/j/SaaLdD2TgoSmz49q7kzuTcB+CZB/bY8Pjhbxzti4Dfa9Klf58bO7d1nzDQZbfWM",
	"y6vagKEl3vydnbn+/yjrw84o/U7LSWQgOODCx8nzHurXP3721b5242vedQ4+Yqv6CWFFJdfUilJMMsxo",
	"o7u9xOh3jC4xc4Efru8O5EKgJ707G36Kdu9a9wIbi5nwhJkPfyUx1SeYMIG+l776EGjgspKTVOCa8os8",
	"tJPBb9+SGOzPakEqDYn3Q1/JZHros4mJsfHYDWMJvptW4eCc91wY+NaEtsTtos8UnuiLU1Yc417ozmJv",
	"evb87xhxURm/D3I2cK+DqvnqfwMAAP//K1XabKsaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
