// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// Defines values for RedeployStatusStatus.
const (
	RedeployStatusStatusCreating RedeployStatusStatus = "Creating"
	RedeployStatusStatusError    RedeployStatusStatus = "Error"
	RedeployStatusStatusQueuing  RedeployStatusStatus = "Queuing"
	RedeployStatusStatusRunning  RedeployStatusStatus = "Running"
)

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// QueueStatus defines model for QueueStatus.
type QueueStatus struct {
	// InQueue キューに入っているチームID_問題IDのリスト
	InQueue *[]string `json:"in_queue,omitempty"`
}

// RedeployRequest defines model for RedeployRequest.
type RedeployRequest struct {
	// ProblemId 問題ID（アルファベット形式、problem_mapping.jsonで定義）
	ProblemId string `json:"problem_id"`

	// TeamId チームID（2桁の数字）
	TeamId string `json:"team_id"`
}

// RedeployStatus defines model for RedeployStatus.
type RedeployStatus struct {
	// Message 状態に関するメッセージ
	Message *string `json:"message,omitempty"`

	// Status 再展開の状態
	Status *RedeployStatusStatus `json:"status,omitempty"`

	// UpdatedAt 最終更新日時
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// RedeployStatusStatus 再展開の状態
type RedeployStatusStatus string

// PostRedeployJSONRequestBody defines body for PostRedeploy for application/json ContentType.
type PostRedeployJSONRequestBody = RedeployRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// キューの状態取得（未使用）
	// (GET /monitor)
	GetQueueStatus(c *gin.Context)
	// 再展開リクエストの送信
	// (POST /redeploy)
	PostRedeploy(c *gin.Context)
	// チーム全体のステータス取得
	// (GET /status/{teamID})
	GetTeamStatus(c *gin.Context, teamID string)
	// 特定の問題のステータス取得
	// (GET /status/{teamID}/{problemID})
	GetProblemStatus(c *gin.Context, teamID string, problemID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetQueueStatus operation middleware
func (siw *ServerInterfaceWrapper) GetQueueStatus(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetQueueStatus(c)
}

// PostRedeploy operation middleware
func (siw *ServerInterfaceWrapper) PostRedeploy(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRedeploy(c)
}

// GetTeamStatus operation middleware
func (siw *ServerInterfaceWrapper) GetTeamStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamID" -------------
	var teamID string

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamStatus(c, teamID)
}

// GetProblemStatus operation middleware
func (siw *ServerInterfaceWrapper) GetProblemStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamID" -------------
	var teamID string

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "problemID" -------------
	var problemID string

	err = runtime.BindStyledParameterWithOptions("simple", "problemID", c.Param("problemID"), &problemID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter problemID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProblemStatus(c, teamID, problemID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/monitor", wrapper.GetQueueStatus)
	router.POST(options.BaseURL+"/redeploy", wrapper.PostRedeploy)
	router.GET(options.BaseURL+"/status/:teamID", wrapper.GetTeamStatus)
	router.GET(options.BaseURL+"/status/:teamID/:problemID", wrapper.GetProblemStatus)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZW1MbRxb+K1Sv31ZGEnYeVm++btjaCzE8baylxlIbJiXNjGdazlKUquiRcQQoBbYD",
	"GF/Wxo6xYgrhrVzKbAT8mGZG4om/sHW65z4jWYRN1ebJg2a6z+37zvm6PYsKallTFawQA+VmkVGYxmWJ",
	"P17TdVWHB01XNawTGfOfy9gwpCkMj/ifUlkrYZRDzGyy2nes1ma1TVarMfNneDY/oBQiMxp8YRBdVqZQ",
	"NYUMIpGKEV6Pua3Yx1XvF/XWF7hAYPlnFVzB494eYedkZfIOvIfnIjYKuqwRWVW4hzus9ga8otvW/BtG",
	"XzO6xeg9Zi6xGuWevxy9OmmtLh9vNkavMtpitXfM3GO1Okr5nn6OMtnJTBalUGZkMnMB5VNIJrgsXJEI",
	"wToY+8fNm8XZkeqk+OdcUhacHyRdl2aSA72Bi1grqTM38J0KNkg8WE1Xb5VweVIuxsN14zhp15n5itW2",
	"WW2VmZustgHlqdWt/VdWe5nNUXeTsqRpsjI1/IWhKoy+tVpPOgffnbQXgsGjS5evJMaCpWQvApk9addH",
	"7E3KaMtefW/trEe35jmNZfBcIiZ0fKci67gI5XBtp4LpyPdJZy/oBHAdDqKz+JM9v8To9vHaK0Y3OGCi",
	"IA8wwQ15KJMdYrQlCuH8wSG1z1ftMdqwd15bHz4AIO9/bf179XhtidFVZjYYPWB0ndEX/ekTqbi/R0u4",
	"DH4plTJkCUgD61Poio4lIh5vVBRFPAmq54Nx+C9jHlS0okRwcVIicS/sZ3OdH0376Q/22nt7/Y29YYay",
	"M5IZuXg+kz2f/WQim8ldyOQymb+jFLqt6mXYDcHG54lcxoP0AkgGLlR0mcyMQ9sSdbwlGXLhUoVMx537",
	"dGJibOgyvO+++7rbbJ+068PTRJMM48sio287rc3Oyn0BTN4HwRjfzvdmmhANVcG0rNxWwURBVYhU4KlQ",
	"JL5k9MrEOPCkopecFUYunZ6SyXTl1nBBLaflAjEKaQMqiSGhvQoJaNmF1srbEDMfCg8BG3OU0eeAKHh1",
	"nyPqEJ7Nh52nr7tbaw5Q6QtmAucujY0y80cOzBVWa0M8MuEVEV4MXRobHRrH+l0MXfgu1g3hS3Y4M5wB",
	"F1UNK5Imoxy6MJwdzgiuTvOEp8uqIhMxKqawgwlNxwUACcoRvYJTvZtxq7N8YD1reqBl5kNrec06WOcM",
	"OIA45kzve+v+PKPbjJrMXLLmm7yFtzzKMdoUdOM/PoHGRxvWyjbs47AKdrup2N837XvLuSFGH/EcNlnt",
	"e1ZbYLXnzPyWP9cZ3bWfvTvaP+x802S0CW8dJzbdD7a7zcfd9oLLWT5NfBuIJ02XIOTRIsqhP2ISnF3Q",
	"xgxNVQwB25FMxkUTVngSJU0ryQW+Pg1dOTQxg6MuOpNSKPMJ/J2vOjiW4PtzOr6Ncuh3aX/gp51pnw76",
	"xcHdq1xOpuoATdr60/jf/upPSc7HSrks6TPREvPKirKetOteXgXViDRlQBB/cWCUh43SutOueaNWDdKv",
	"4cV4Yn215fDErYeLi3eMPuDVeh9fFZQI3cN9a/FlcIebirXSYPRxYKb9PqoWAtvRhr3+CrAagu4BMJLu",
	"Cv+OPuzAgHj5g7UCcPM1lPmwe/hN2HYMTWOqQdyRhsRIxAa5rBZnBodRUIRlufrzytczubR1dACT5a5U",
	"EjIrqEJcgeDqAZjqHE+DwTCqeKrhYQ+dpBqjTXaAeH3zA2jZfrhaXmf0wdHPjwFFgw1pf1+pUMAatMRB",
	"Rlucg2Fngp7Y9RVr8QWYvXiaJuII5rtSSS5edwZwEAKde5vW4h5QJpIHUJJC6/9LiMkgHLyUnmI9o28Z",
	"3UB+2pzzgBiz3MExgbLRq2EfffAx2hAGP+JMcMVHrU5gKWbSATcwV2hol7bJhr3Pd0PylxvnU+xwvrtF",
	"GW3wPxcF5ZOcGphF1/wFfSGUUAcvFMDSyB9OiSWppGOpODOqfOYewfysRZohaN6dx9azZnLSIp3Wk9FJ",
	"fXa319ZeA00uMR+e1yulUtjRwD4N+z9z9vPdZBdjzSG6rDe8zl5Ja6Vhb5jRllD/6XhjxZsxCYGEJ3Sf",
	"Fn88R48ONwOz2Zs0YjiLkNKzhPOjGlJ+oaPTwp7VehKWaNuMLvIh7As4v7gxNRvRgkmiCkjqaSpN0qUy",
	"JlgHt099HJXhKxC2KOWKeREiis6hYAl/ySE2f1b5B5M2Asj/7cHTg61/Egwe/JKPctUUunrteoTMH5un",
	"1vKa2/mitv1zaz/bI8J2iFdSsShD7qTSWGjkD6I/XCU8yFiOIDYmigcdymfsCIFh+4CZe1Ex7mLDmm8e",
	"7T+KM03QLEB4JwWJdE/Pau407k193yTo3pbXCc7GdUcG/Obonvp17udc1r5gpsloq2dUXr0GDCzxnu/s",
	"Pev/r1md7lzS74Sc1AYE+y/+MkneQ/H6R86+etdufMX55uAjtqqf+FVUcl2tKMUkw4w2ultLjH7L6BIz",
	"F/iB+t5ALgTY6N3T8JOze7+6G9hYTIOnzHz0KwmoPsGEW+dHG1ef1hm4oOTtKXA1+Xke6GTwG7ek3vVn",
	"tSCVhsT7oS9lMj306cTE2HjsVrEE302rcFjOey4MfFNCW+JG0e8UntCLt6w4xr3QncXe3Oz5ny/icjJ+",
	"B+Rs4F4BVfPV/wYAAP//DeQ5bJkaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
